# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-08 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20180402_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guset',
            new_name='Guest',
        ),
    ]
